# Generated by Django 3.1.2 on 2020-10-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OderContents',
            new_name='OrderContents',
        ),
    ]
